-- MySQL Script generated by MySQL Workbench
-- Mon Feb 22 20:38:21 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gerenciador_de_tarefas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gerenciador_de_tarefas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gerenciador_de_tarefas` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `gerenciador_de_tarefas` ;

-- -----------------------------------------------------
-- Table `gerenciador_de_tarefas`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gerenciador_de_tarefas`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(200) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gerenciador_de_tarefas`.`peoples`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gerenciador_de_tarefas`.`peoples` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `age` INT UNSIGNED NOT NULL,
  `document` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gerenciador_de_tarefas`.`people_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gerenciador_de_tarefas`.`people_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `people_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_people_user_peoples_idx` (`people_id` ASC) VISIBLE,
  INDEX `fk_people_user_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_people_user_peoples`
    FOREIGN KEY (`people_id`)
    REFERENCES `gerenciador_de_tarefas`.`peoples` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_people_user_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `gerenciador_de_tarefas`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
